Mosi-Rivera/RetoCompraServer

- app.js
- constants/CURRENCIES.js
- constants/SECTIONS.js
- constants/SIZES.js
- constants/SORT.js
- controllers/product_controllers.js
- models/Product.js
- models/Variant.js
- routes/product_routes.js
- seed/seed_test_products.js
Adds:
1. Product model
2. Variant model
3. products route
4. getProducts controller
5. seed products script
> Get products

- controllers/product_controllers.js
- models/Product.js
- models/Variant.js
- routes/product_routes.js
- seed/seed_test_products.js
Modifies product / variant schemas to make queries simpler. (duplicates needed product fields in variant and adds indexing)
Rewrites getProducts controller using simpler queries.
Adds products text search controller.
> New schema design and simplified product queries

- app.js
- controllers/auth_controllers.js
- models/user.js
- package.json
- routes/auth_route.js
Adding register route functionality
> Register route

- app.js
- constants/CURRENCIES.js
- constants/SECTIONS.js
- constants/currency.js
- constants/role.js
- constants/section.js
- constants/size.js
- controllers/auth_controllers.js
- controllers/product_controllers.js
- models/Product.js
- models/Variant.js
- models/user.js
- routes/auth_route.js
- seed/seed_test_products.js
- utils/jwt.js
Changed snake_case declarations to camelCase.
Changed env variables.
> Camel case and env_variables

- app.js
- controllers/auth_controllers.js
- middlewares/authorization.js
- routes/auth_route.js
- utils/jwt.js
added 
- middleware folder 
- authorization middleware file
> add authorization middleware

- app.js
- controllers/auth_controllers.js
> Fix Bug Register

- controllers/auth_controllers.js
- package.json
adding a decrypt password functionality to the server
> decryptPasswordServer

- controllers/auth_controllers.js
added next to the login controller and error handler
> add next to controllers and errors

- app.js
- controllers/auth_controllers.js
- middlewares/authorization.js
fix duplicated email message and removed console.logs
> Fix duplicated email message

- controllers/auth_controllers.js
Gets refersh token from cookies insted of body which is always undefined
> Fix remove old refresh token bug

- controllers/product_controllers.js
- routes/product_routes.js
added route and controller to get product info
> add getVariantController

- models/Variant.js
> Fix: Variant size filter bug.

- controllers/cart_controllers.js
- controllers/product_controllers.js
- middlewares/authorization.js
> Console log fix

- controllers/order_controllers.js
- models/order.js
added tax calculation and address naming convention
> add tax calc and naming convention

- controllers/product_controllers.js
- models/Variant.js
El anterior no estaba funcionando bien asi que tuve que usar aggregation.
> Fix: critical dearch controller fix. Had to use aggregation :/

- app.js
- controllers/product_controllers.js
- models/Product.js
- package.json
- routes/product_routes.js
- utils/mailer.js
Adding routes and controller for Crud Products and variants
> Crud productv1

- controllers/order_controllers.js
- controllers/product_controllers.js
- models/order.js
- routes/order_routes.js
- routes/product_routes.js
added
-get all products route
- get all productController
> Confirmation updates

- .gitignore
- controllers/product_controllers.js
- utils/mailer.js
Adding size to CRUD controllers. Need to understand how size is actually captured from the user select. Lets review
> Crud productv2

- controllers/order_controllers.js
- routes/order_routes.js
removed practice controller and route
- order controller 
- order route
> deleted prototype controller/route

- controllers/product_controllers.js
- utils/Imageupload.js
> Fix cloudinary

- controllers/product_controllers.js
- routes/product_routes.js
both routes work properly
Routes
- change the api route endpoint to be /deleteVariant and /deleteProduct
controllers:
-minors changes so the formula could read the id
- forgot to delete all my comments from the delete variant controller :/
> Crud delete
